# Generated by Django 6.0.3 on 2026-03-11 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('class_identity', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='班级标识 (ClassIdentity)')),
                ('class_plans_json', models.JSONField(blank=True, default=dict, verbose_name='课表 JSON')),
                ('class_plans_version', models.IntegerField(default=0, verbose_name='课表版本')),
                ('time_layouts_json', models.JSONField(blank=True, default=dict, verbose_name='时间表 JSON')),
                ('time_layouts_version', models.IntegerField(default=0, verbose_name='时间表版本')),
                ('subjects_json', models.JSONField(blank=True, default=dict, verbose_name='科目 JSON')),
                ('subjects_version', models.IntegerField(default=0, verbose_name='科目版本')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='默认设置 JSON')),
                ('settings_version', models.IntegerField(default=0, verbose_name='默认设置版本')),
                ('policy_json', models.JSONField(blank=True, default=dict, verbose_name='策略 JSON')),
                ('policy_version', models.IntegerField(default=0, verbose_name='策略版本')),
                ('components_json', models.JSONField(blank=True, default=dict, verbose_name='组件 JSON')),
                ('components_version', models.IntegerField(default=0, verbose_name='组件版本')),
                ('credential_json', models.JSONField(blank=True, default=dict, verbose_name='凭据 JSON')),
                ('credential_version', models.IntegerField(default=0, verbose_name='凭据版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '班级组',
                'verbose_name_plural': '班级组',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ClassIsland 集控', max_length=200, verbose_name='组织名称')),
                ('core_version', models.CharField(default='2.0.0.0', max_length=20, verbose_name='核心版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='客户端 UID')),
                ('client_id', models.CharField(blank=True, default='', max_length=100, verbose_name='客户端班级标识')),
                ('client_mac', models.CharField(blank=True, default='', max_length=20, verbose_name='MAC 地址')),
                ('hostname', models.CharField(blank=True, default='', max_length=200, verbose_name='主机名')),
                ('status', models.IntegerField(choices=[(0, '待审批'), (1, '已批准'), (2, '已封禁')], default=1, verbose_name='状态')),
                ('current_session_id', models.CharField(blank=True, default='', max_length=100, verbose_name='当前会话 ID')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.classgroup', verbose_name='所属班级组')),
            ],
            options={
                'verbose_name': '客户端',
                'verbose_name_plural': '客户端',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, '默认事件'), (1, '授权成功'), (2, '授权失败'), (4, '应用设置更新'), (5, '换课完成'), (6, '课表更新'), (7, '时间表更新'), (8, '科目更新'), (9, '应用崩溃'), (10, '应用启动'), (11, '应用退出'), (12, '插件安装'), (13, '插件卸载')], default=0, verbose_name='事件类型')),
                ('payload', models.BinaryField(blank=True, default=b'', verbose_name='载荷 (protobuf bytes)')),
                ('timestamp_utc', models.DateTimeField(verbose_name='事件时间 (UTC)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.client')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp_utc'],
            },
        ),
        migrations.CreateModel(
            name='ConfigUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_guid', models.CharField(max_length=100, verbose_name='请求 GUID')),
                ('config_type', models.IntegerField(choices=[(0, '未指定'), (1, '应用设置'), (2, '档案'), (3, '当前组件'), (4, '工作流'), (5, '日志'), (6, '插件列表')], default=0, verbose_name='配置类型')),
                ('payload_json', models.JSONField(default=dict, verbose_name='配置 JSON')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_uploads', to='core.client')),
            ],
            options={
                'verbose_name': '配置回传',
                'verbose_name_plural': '配置回传',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='core.organization'),
        ),
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.IntegerField(choices=[(10, 'Ping'), (11, 'Pong'), (101, '重启应用'), (102, '发送通知'), (103, '数据更新'), (104, '获取客户端配置')], verbose_name='命令类型')),
                ('payload', models.BinaryField(blank=True, default=b'', verbose_name='载荷 (protobuf bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False, verbose_name='已送达')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_commands', to='core.client')),
            ],
            options={
                'verbose_name': '待下发命令',
                'verbose_name_plural': '待下发命令',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.BigIntegerField(db_index=True, verbose_name='PGP Key ID')),
                ('public_key_armored', models.TextField(verbose_name='公钥 (ASCII Armored)')),
                ('private_key_armored', models.TextField(verbose_name='私钥 (ASCII Armored)')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前使用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypairs', to='core.organization')),
            ],
            options={
                'verbose_name': '服务器密钥',
                'verbose_name_plural': '服务器密钥',
            },
        ),
    ]
