# Generated by Django 6.0.3 on 2026-03-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_connection_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='课表 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plans', to='core.organization')),
            ],
            options={
                'verbose_name': '课表配置',
                'verbose_name_plural': '课表配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_class_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.classplanconfig', verbose_name='关联课表配置'),
        ),
        migrations.CreateModel(
            name='ComponentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='组件 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.organization')),
            ],
            options={
                'verbose_name': '组件配置',
                'verbose_name_plural': '组件配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.componentconfig', verbose_name='关联组件'),
        ),
        migrations.CreateModel(
            name='CredentialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='凭据 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.organization')),
            ],
            options={
                'verbose_name': '凭据配置',
                'verbose_name_plural': '凭据配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.credentialconfig', verbose_name='关联凭据'),
        ),
        migrations.CreateModel(
            name='DefaultSettingsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='设置 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_settings', to='core.organization')),
            ],
            options={
                'verbose_name': '默认设置配置',
                'verbose_name_plural': '默认设置配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_default_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.defaultsettingsconfig', verbose_name='关联默认设置'),
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='策略 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.organization')),
            ],
            options={
                'verbose_name': '策略配置',
                'verbose_name_plural': '策略配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.policyconfig', verbose_name='关联策略'),
        ),
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='科目 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.organization')),
            ],
            options={
                'verbose_name': '科目配置',
                'verbose_name_plural': '科目配置',
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='linked_subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.subjectconfig', verbose_name='关联科目配置'),
        ),
        migrations.CreateModel(
            name='TimeLayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('identifier', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标识')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='时间表 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_layouts', to='core.organization')),
            ],
            options={
                'verbose_name': '时间表配置',
                'verbose_name_plural': '时间表配置',
            },
        ),
        migrations.AddField(
            model_name='classplanconfig',
            name='time_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_plans', to='core.timelayoutconfig', verbose_name='依赖时间表'),
        ),
    ]
